### ISSUE TITLE
Associated Laguerre Polynomials with half-integer values

### ISSUE THREAD

**Issue by ajarifi** [ohno/Antique.jl#30]
Associated Laguerre polynomials in hydrogen atoms do not accommodate half-integer values of n and k. Generalizing them for other cases would be beneficial. I believe this limitation arises because factorials only accept integer numbers.

**Comment by ajarifi** [comment]
it is better to use a recursive formula, rather than the summation.

**Comment by ohno** [comment]
Of course, we can extend the current model or add new model if there are useful applications. However, I don't know the importance of half-integer quantum numbers because I have never used them in hydrogen atoms. Do you have examples of half-integer quantum numbers?

I think the current version is sufficient. It is natural for $n$ and $k$ to be integers because associated Laguerre polynomials are defined using Rodrigues' formula in many textbooks.

**Comment by ajarifi** [comment]
Sorry, I think for k can be a half-integer. the example is for the 3D isotropic harmonic oscillator potential. 
Last night, I worked on it. I will try to pull request this week.

**Comment by ohno** [comment]
I understand the true problem now. The generalized Laguerre polynomials $L_n^{(\alpha)}(x)$, not the associated Laguerre polynomials $L_n^{k}(x)$, are used in the 3-dimensional harmonic oscillator. The generalized Laguerre polynomials $L_n^{(\alpha)}(x)$ accept $\alpha\in\mathbb{R}$. It also relates to #7.
